### ISSUE TITLE
Bit type doesn't implement pgtype.TextDecoder

### ISSUE THREAD

**Issue by mjibson** [jackc/pgtype#7]
Running a query like `SELECT B'1001111101101110001101100010110'` is panicing:

```
panic: interface conversion: *pgtype.Bit is not pgtype.TextDecoder: missing method DecodeText

goroutine 44631 [running]:
main.compareConns.func1.1(0xc00018eda5, 0x8, 0x0, 0x0, 0xc000792200, 0x63)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cmd/smithcmp/main.go:246 +0x195
panic(0x136d620, 0xc000476240)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgx.(*Rows).Values(0xc000f026e0, 0x1595d01, 0xc000f026e0, 0xc000792200, 0x63, 0x265dde0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/jackc/pgx/query.go:296 +0x64e
main.(*Conn).Values(0xc0002da100, 0x1942a60, 0xc000bd9180, 0x0, 0x0, 0xc000792200, 0x63, 0x0, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cmd/smithcmp/conn.go:101 +0x157
main.compareConns.func1(0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/cmd/smithcmp/main.go:251 +0x1b7
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008de960, 0xc000851f80)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Comment by mjibson** [comment]
This is with 3.5.0, but seems like it's still present based on the code.

**Comment by jackc** [comment]
Not sure why it wasn't implemented given that Bit is implemented in terms of Varbit which did have text format support.

Also backported to pgx v3.
